services:
  postgresql:
    image: bitnami/postgresql:latest

    ports:
      - "5432:5432"

    environment:
      - POSTGRESQL_USER=postgresql
      - POSTGRESQL_PASSWORD=postgresql
      - POSTGRESQL_DATABASE=tasks